{{- range $repo_key, $repo_value := .Values.configs.repositories }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $repo_key }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  {{- with $.Values.configs.repositoriesAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
data:
  {{- range $key, $value := $repo_value }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
